"""
Command line entry point: connect to a SmartKnob over USB and drive the host's
volume/brightness with it.
"""

import argparse
import logging
import math
import os
import sys
import threading
import time

# The checked-in *_pb2.py files were generated by an older protoc, which the C++
# protobuf runtime refuses to load. Pure-python parsing handles them fine and is
# more than fast enough for 36-byte messages.
os.environ.setdefault('PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION', 'python')

_python_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# proto_gen/smartknob_pb2.py imports nanopb_pb2 as a top-level module, so
# proto_gen itself has to be importable too.
for _path in (_python_root, os.path.join(_python_root, 'proto_gen')):
    if _path not in sys.path:
        sys.path.insert(0, _path)

import serial
import serial.tools.list_ports

from proto_gen import smartknob_pb2
from smartknob_io import (
    SMARTKNOB_BAUD,
    Smartknob,
    ask_for_serial_port,
)

from .controller import (
    DeckController,
    KnobState,
)
from .controls import (
    ALL_CONTROLS,
    ControlUnavailable,
    build_controls,
)

logger = logging.getLogger('smartknob_deck')

DEFAULT_CONTROLS = ['volume', 'brightness']

# USB-serial chips used by the SmartKnob View (CH340), the NanoFOC and other
# ESP32-S3 boards (native USB / CP210x)
KNOWN_USB_IDS = [
    (0x1a86, 0x7523),  # CH340
    (0x10c4, 0xea60),  # CP210x
]
ESPRESSIF_VID = 0x303a

RECONNECT_DELAY_SECONDS = 2.0


def config_to_proto(config):
    """Convert a KnobConfig into the wire message the firmware expects."""
    message = smartknob_pb2.SmartKnobConfig()
    message.position = config.position
    message.position_nonce = config.position_nonce
    message.min_position = config.min_position
    message.max_position = config.max_position
    message.position_width_radians = config.position_width_radians
    message.detent_strength_unit = config.detent_strength_unit
    message.endstop_strength_unit = config.endstop_strength_unit
    message.snap_point = config.snap_point
    message.text = config.text
    message.led_hue = config.led_hue
    return message


def state_from_proto(state):
    return KnobState(
        current_position=state.current_position,
        press_nonce=state.press_nonce,
        config_text=state.config.text,
    )


def candidate_ports():
    ports = sorted(serial.tools.list_ports.comports(), key=lambda p: p.device)
    return [p for p in ports
            if (p.vid, p.pid) in KNOWN_USB_IDS or p.vid == ESPRESSIF_VID]


def find_port():
    candidates = candidate_ports()
    if len(candidates) == 1:
        port = candidates[0]
        logger.info('Using %s (%s)', port.device, port.description)
        return port.device
    if len(candidates) > 1:
        print('Multiple SmartKnob-like devices found; pass --port to skip this.')
    else:
        print('No SmartKnob detected automatically; pick a port manually.')
    return ask_for_serial_port()


def run_once(port, controls, poll_interval):
    """
    Connect and run until the knob goes away or the user interrupts.

    Returns True if it's worth reconnecting, False if we should stop.
    """
    with serial.Serial(port, SMARTKNOB_BAUD, timeout=1.0) as ser:
        # The firmware boots into its plaintext protocol, where stray bytes are
        # interpreted as commands ('C' starts a motor recalibration!). A single
        # zero byte switches it to the protobuf protocol before we send anything
        # that could be misread.
        ser.write(b'\0')

        knob = Smartknob(ser)
        knob.start()
        try:
            # The controller is driven from both the serial read thread (state
            # handler) and this thread (tick), so serialize access to it.
            lock = threading.Lock()
            controller = DeckController(
                controls,
                lambda config: knob.set_config(config_to_proto(config)),
                poll_interval=poll_interval,
            )

            knob.add_handler('log', lambda msg: logger.debug('knob: %s', msg.msg))
            knob.add_handler('smartknob_state', lambda state: _handle_state(
                lock, controller, state))

            with lock:
                controller.start()
            knob.request_state()

            while True:
                if not (knob.read_thread.is_alive() and knob.write_thread.is_alive()):
                    logger.warning('Lost connection to the knob')
                    return True
                with lock:
                    controller.tick()
                time.sleep(0.02)
        except KeyboardInterrupt:
            return False
        finally:
            knob.shutdown()


def _handle_state(lock, controller, state):
    with lock:
        controller.handle_state(state_from_proto(state))


def _self_test(keys):
    """Report what each requested control can do here, without needing a knob."""
    ok = True
    for key in keys:
        factory = ALL_CONTROLS.get(key)
        if factory is None:
            print(f'{key}: unknown control')
            ok = False
            continue
        control = factory()
        try:
            value = control.read()
        except ControlUnavailable as e:
            print(f'{control.label}: unavailable - {e}')
            ok = False
            continue
        span = control.max_value - control.min_value
        step = math.degrees(control.position_width_radians)
        print(f'{control.label}: {value} '
              f'(range {control.min_value}-{control.max_value}, '
              f'{span + 1} detents, {step:.2f}\N{DEGREE SIGN} each, '
              f'{span * step:.0f}\N{DEGREE SIGN} end to end)')
    return 0 if ok else 1


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog='python -m smartknob_deck',
        description='Use a SmartKnob to control this computer\'s volume and '
                    'brightness. Press the knob to switch between controls.')
    parser.add_argument('--port', help='serial port of the SmartKnob '
                                       '(auto-detected if omitted)')
    parser.add_argument('--controls', default=','.join(DEFAULT_CONTROLS),
                        help='comma-separated controls to cycle through. '
                             f'Available: {", ".join(sorted(ALL_CONTROLS))} '
                             '(default: %(default)s)')
    parser.add_argument('--poll-interval', type=float, default=2.0,
                        help='seconds between checks for changes made outside '
                             'the knob (default: %(default)s)')
    parser.add_argument('--no-reconnect', action='store_true',
                        help='exit instead of waiting for the knob to come back')
    parser.add_argument('--list-ports', action='store_true',
                        help='list serial ports that look like a SmartKnob and exit')
    parser.add_argument('--self-test', action='store_true',
                        help='report what each control reads right now and exit '
                             '(no knob required)')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='include debug logging')
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s %(levelname)-7s %(message)s',
        datefmt='%H:%M:%S',
    )

    if args.list_ports:
        found = candidate_ports()
        if not found:
            print('No SmartKnob-like serial ports found.')
        for port in found:
            print(f'{port.device} - {port.description}')
        return 0

    keys = [key.strip() for key in args.controls.split(',') if key.strip()]
    if args.self_test:
        return _self_test(keys)

    try:
        controls = build_controls(keys)
    except ControlUnavailable as e:
        parser.error(str(e))

    logger.info('Controls: %s (press the knob to switch)',
                ', '.join(c.label for c in controls))

    while True:
        try:
            port = args.port or find_port()
            reconnect = run_once(port, controls, args.poll_interval)
        except KeyboardInterrupt:
            reconnect = False
        except (serial.SerialException, OSError) as e:
            logger.warning('Serial error: %s', e)
            reconnect = True

        if not reconnect or args.no_reconnect:
            logger.info('Bye')
            return 0
        logger.info('Reconnecting in %.0fs...', RECONNECT_DELAY_SECONDS)
        time.sleep(RECONNECT_DELAY_SECONDS)


if __name__ == '__main__':
    sys.exit(main())
